name: Software Testing Analysis

on: ["push"]

jobs:
  software-fuzzing-analysis:
    name: Software Testing Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      
      - name: Run Testing Analysis
        run: python detectors/test2.py
